# Generated by Django 4.1.7 on 2023-03-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geofree_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='views',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
