# Generated by Django 4.1.7 on 2023-03-27 14:33

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geofree_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
