# Generated by Django 4.1.7 on 2023-03-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geofree_api', '0002_alter_item_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='likes',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
