# Generated by Django 4.1 on 2023-03-05 14:55

from django.db import migrations, models
import django.db.models.deletion
import geofree_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('geofree_api', '0006_alter_item_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='available',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.CreateModel(
            name='ItemImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to=geofree_api.models.upload_path)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='geofree_api.item')),
            ],
        ),
    ]
