# Generated by Django 4.1 on 2023-03-06 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geofree_api', '0010_alter_item_latitude_alter_item_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='picture',
        ),
    ]
