# Generated by Django 4.1 on 2023-03-03 14:23

from django.db import migrations, models
import geofree_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('geofree_api', '0002_remove_item_username_delete_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='picture',
            field=models.ImageField(null=True, upload_to=geofree_api.models.upload_path),
        ),
    ]
