# Generated by Django 4.1 on 2023-03-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geofree_api', '0004_rename_category_item_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='available',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
