# Generated by Django 4.1 on 2023-03-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geofree_api', '0007_alter_item_available_itemimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='item',
            name='latitude',
            field=models.IntegerField(max_length=20, null=True),
        ),
    ]
