# Generated by Django 4.1 on 2023-03-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geofree_api', '0008_remove_item_longitude_alter_item_latitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='longitude',
            field=models.IntegerField(max_length=20, null=True),
        ),
    ]
